# Mappings
Mappings=

[Delay]
# Lowercase (ms)
Lowercase=400
# Uppercase (ms)
Uppercase=700

[Leader]
# Space
Space=True
# Left Arrow
Left=False
# Right Arrow
Right=False
# Up Arrow
Up=False
# Down Arrow
Down=False
# Alt/AltGr
Alt=False

[Leader/Custom]
# Custom Leader 1
CustomKeyEnabled=False
#   ↳ Key
CustomKey=
# Custom Leader 2 (hand-split)
CustomKey2Enabled=False
#   ↳ Key
CustomKey2=

[AppFilter]
# Mode
Mode=Disabled
# Blacklist
Blacklist=
# Whitelist
Whitelist=

[Overlay]
# Show overlay while cycling
Enabled=False
# Vertical position
Row=Top
# Horizontal position
Column=Col4

[Theme]
# UI theme (schnelle-umlaute|dark|light|contrast)
Theme=schnelle-umlaute
