// generated by gemini
pragma ComponentBehavior: Bound
import QtQuick
import QtQuick.Layouts

Item {
    id: root

    // --- Proprietà configurabili ---
    property real value: 0
    property real minimum: 0
    property real maximum: 100
    property real step: 5

    property color accentColor: "white"
    property color barOffColor: Qt.rgba(accentColor.r, accentColor.g, accentColor.b, 0.35)
    property color dotColor: "white"
    property int handleSize: 16
    property int dotSize: 10
    property int barThickness: 4
    property int barCornerRadius: 50 // 50 -> pill; 0 -> rectangle ==> percentage of the height
    property bool cutBar: true // true -> cut the bar to end at the start of the dot; false -> do not cut the bar, so it ends int the center of the dot
    property bool scrollable: true // true -> go forward/backwards of step amount with the scroll wheel
    property bool changeValueAfterMoved: false

    property bool isUserInteracting: false

    property Component handleDelegate: null

    // Segnale emesso quando l'utente muove lo slider
    signal moved(real newValue)

    implicitHeight: handleSize
    implicitWidth: 200

    // Calcolo interno della posizione del pallino
    readonly property real visualPos: ((value - minimum) / (maximum - minimum)) * (width - handleSize)

    // Barra di sfondo
    Rectangle {
        anchors.verticalCenter: parent.verticalCenter
        width: parent.width
        height: root.barThickness
        color: root.barOffColor
        radius: height * (root.barCornerRadius / 100)

        // Parte attiva
        Rectangle {
            width: root.cutBar ? (root.visualPos) : (root.visualPos + (root.handleSize)) //  + (root.handleSize / 2) - (root.dotSize / 3)
            height: parent.height
            color: root.accentColor
            radius: height * (root.barCornerRadius / 100)
        }
    }

    Loader {
        id: handleLoader
        x: root.visualPos
        y: (parent.height - height) / 2
        width: root.handleSize
        height: root.handleSize

        // Se non passiamo nulla da fuori, usiamo un pallino bianco di default
        sourceComponent: root.handleDelegate ? root.handleDelegate : defaultHandle
    }

    // Componente di default (quello semplice)
    Component {
        id: defaultHandle
        Rectangle {
            radius: root.dotSize / 2
            color: root.dotColor
        }
        // // Pallino
        // Rectangle {
        //     // id: handle
        //     // x: root.visualPos
        //     // y: (parent.height - height) / 2
        //     width: root.dotSize; height: root.dotSize
        //     radius: width / 2;
        //     color: "transparent"
        //     border.color: root.dotColor
        //     border.width: root.dotSize / 5
        // }
    }

    // // Pallino
    // Rectangle {
    //     id: handle
    //     x: root.visualPos
    //     y: (parent.height - height) / 2
    //     width: root.dotSize; height: root.dotSize
    //     radius: width / 2;
    //     color: "transparent"
    //     border.color: root.dotColor
    //     border.width: root.dotSize / 5

    //     // Effetto "buco" come nella tua foto
    //     // Rectangle {
    //     //     anchors.centerIn: parent
    //     //     width: parent.width * 0.4; height: width
    //     //     radius: width / 2; color: "#1a1a1a"
    //     // }
    // }

    MouseArea {
        anchors.fill: parent

        // Funzione di utilità per calcolare il valore in base alla coordinata X del mouse
        function calculateValue(mouseX) {
            let pos = Math.max(0, Math.min(mouseX - parent.handleSize / 2, root.width - parent.handleSize));
            let ratio = pos / (root.width - parent.handleSize);
            return parent.minimum + (ratio * (parent.maximum - parent.minimum));
        }

        onPressed: mouse => {
            root.isUserInteracting = true;
            let val = calculateValue(mouse.x);

            // Aggiorniamo sempre la visualizzazione locale
            root.value = val;

            // Se NON dobbiamo aspettare il rilascio, emettiamo subito
            if (!root.changeValueAfterMoved) {
                root.moved(val);
            }
        }

        onPositionChanged: mouse => {
            if (pressed) {
                let val = calculateValue(mouse.x);

                // Aggiorniamo il pallino visivamente
                root.value = val;

                // Emettiamo il segnale solo se il cambio deve essere immediato
                if (!root.changeValueAfterMoved) {
                    root.moved(val);
                }
            }
        }

        onReleased: mouse => {
            root.isUserInteracting = false;

            // Se avevamo attivato il cambio "ritardato", emettiamo il segnale ora
            if (root.changeValueAfterMoved) {
                let finalVal = calculateValue(mouse.x);
                root.moved(finalVal);
            }
        }

        scrollGestureEnabled: root.scrollable

        onWheel: wheel => {
            let newValue = root.value + (wheel.angleDelta.y > 0 ? root.step : -root.step);
            newValue = Math.max(root.minimum, Math.min(newValue, root.maximum));

            // Per la rotella di solito si preferisce il feedback immediato
            root.value = newValue;
            root.moved(newValue);
        }
    }
}
