// generated by gemini
import QtQuick
import QtQuick.Layouts

Item {
    id: root
    
    // --- Proprietà configurabili ---
    property real value: 0
    property real minimum: 0
    property real maximum: 100
    
    property color accentColor: "white"
    property int handleSize: 16
    
    // Segnale emesso quando l'utente muove lo slider
    signal moved(real newValue)

    implicitHeight: handleSize
    implicitWidth: 200

    // Calcolo interno della posizione del pallino
    readonly property real visualPos: ((value - minimum) / (maximum - minimum)) * (width - handleSize)

    // Barra di sfondo
    Rectangle {
        anchors.centerY: parent.centerY
        width: parent.width; height: 4
        color: "#30ffffff"; radius: 2
        
        // Parte attiva
        Rectangle {
            width: root.visualPos + (root.handleSize / 2)
            height: parent.height; color: root.accentColor; radius: 2
        }
    }

    // Pallino
    Rectangle {
        id: handle
        x: root.visualPos
        y: (parent.height - height) / 2
        width: root.handleSize; height: root.handleSize
        radius: width / 2; color: "white"
        
        // Effetto "buco" come nella tua foto
        Rectangle {
            anchors.centerIn: parent
            width: parent.width * 0.4; height: width
            radius: width / 2; color: "#1a1a1a" 
        }
    }

    MouseArea {
        anchors.fill: parent
        onPositionChanged: (mouse) => {
            if (pressed) {
                let pos = Math.max(0, Math.min(mouse.x - handleSize/2, root.width - handleSize));
                let ratio = pos / (root.width - handleSize);
                let newValue = minimum + (ratio * (maximum - minimum));
                root.moved(newValue); // Emettiamo il segnale
            }
        }
        onPressed: (mouse) => {
            let pos = Math.max(0, Math.min(mouse.x - handleSize/2, root.width - handleSize));
            let ratio = pos / (root.width - handleSize);
            root.moved(minimum + (ratio * (maximum - minimum)));
        }
    }
}