// generated by gemini
import QtQuick
import QtQuick.Layouts

Item {
    id: root
    
    // --- Proprietà configurabili ---
    property real value: 0
    property real minimum: 0
    property real maximum: 100
    property real step: 5
    
    property color accentColor: "white"
    property color barOffColor: Qt.rgba(accentColor.r, accentColor.g, accentColor.b, 0.35)
    property color dotColor: "white"
    property int handleSize: 16
    property int dotSize: 10
    property int barThickness: 4
    property int barCornerRadius: 50 // 50 -> pill; 0 -> rectangle ==> percentage of the height
    property bool cutBar: true // true -> cut the bar to end at the start of the dot; false -> do not cut the bar, so it ends int the center of the dot
    property bool scrollable: true // true -> go forward/backwards of step amount with the scroll wheel
    property bool changeValueAfterMoved: false

    property bool isUserInteracting: false

    property Component handleDelegate: null
    
    // Segnale emesso quando l'utente muove lo slider
    signal moved(real newValue)

    implicitHeight: handleSize
    implicitWidth: 200

    // Calcolo interno della posizione del pallino
    readonly property real visualPos: ((value - minimum) / (maximum - minimum)) * (width - handleSize)

    // Barra di sfondo
    Rectangle {
        anchors.verticalCenter: parent.verticalCenter
        width: parent.width
        height: barThickness
        color: root.barOffColor
        radius: height*(root.barCornerRadius/100)
        
        // Parte attiva
        Rectangle {
            width: cutBar ? (root.visualPos + (root.handleSize / 2) - (root.dotSize/3)) : (root.visualPos + (root.handleSize / 2))
            height: parent.height
            color: root.accentColor
            radius: height*(root.barCornerRadius/100)
        }
    }

    Loader {
        id: handleLoader
        x: root.visualPos
        y: (parent.height - height) / 2
        width: root.handleSize
        height: root.handleSize
        
        // Se non passiamo nulla da fuori, usiamo un pallino bianco di default
        sourceComponent: root.handleDelegate ? root.handleDelegate : defaultHandle
    }

    // Componente di default (quello semplice)
    Component {
        id: defaultHandle
        Rectangle {
            radius: root.dotSize / 2
            color: root.dotColor
        }
        // // Pallino
        // Rectangle {
        //     // id: handle
        //     // x: root.visualPos
        //     // y: (parent.height - height) / 2
        //     width: root.dotSize; height: root.dotSize
        //     radius: width / 2;
        //     color: "transparent"
        //     border.color: root.dotColor
        //     border.width: root.dotSize / 5
        // }
    }

    // // Pallino
    // Rectangle {
    //     id: handle
    //     x: root.visualPos
    //     y: (parent.height - height) / 2
    //     width: root.dotSize; height: root.dotSize
    //     radius: width / 2;
    //     color: "transparent"
    //     border.color: root.dotColor
    //     border.width: root.dotSize / 5
        
    //     // Effetto "buco" come nella tua foto
    //     // Rectangle {
    //     //     anchors.centerIn: parent
    //     //     width: parent.width * 0.4; height: width
    //     //     radius: width / 2; color: "#1a1a1a" 
    //     // }
    // }

    Ecco la versione esatta che avevi richiesto, basata sulla tua prima soluzione preferita, con l'aggiunta della logica per changeValueAfterMoved.

Questa versione garantisce che il pallino si muova sempre visivamente, ma emette il segnale di cambio valore (moved) solo quando decidi tu tramite la proprietà.
QML

    MouseArea {
        anchors.fill: parent
        
        // Funzione di utilità per calcolare il valore in base al mouse
        function valueFromMouse(mouseX) {
            let pos = Math.max(0, Math.min(mouseX - handleSize/2, root.width - handleSize));
            let ratio = pos / (root.width - handleSize);
            return minimum + (ratio * (maximum - minimum));
        }

        onPressed: (mouse) => {
            root.isUserInteracting = true;
            let newValue = valueFromMouse(mouse.x);
            
            // Aggiorniamo la barra subito visivamente
            root.value = newValue; 
            
            // Se NON vogliamo aspettare il rilascio, emettiamo subito
            if (!root.changeValueAfterMoved) {
                root.moved(newValue);
            }
        }

        onPositionChanged: (mouse) => {
            if (pressed) {
                let newValue = valueFromMouse(mouse.x);
                
                // Il pallino segue SEMPRE il mouse visivamente
                root.value = newValue;
                
                // Emettiamo il segnale durante il drag solo se la funzione è disattivata
                if (!root.changeValueAfterMoved) {
                    root.moved(newValue);
                }
            }
        }

        onReleased: (mouse) => {
            root.isUserInteracting = false;
            let finalValue = valueFromMouse(mouse.x);
            
            // Se la funzione è attiva, emettiamo il segnale SOLO ora che abbiamo rilasciato
            if (root.changeValueAfterMoved) {
                root.moved(finalValue);
            }
        }

        // Gestione rotella
        onWheel: (wheel) => {
            let newValue = root.value + (wheel.angleDelta.y > 0 ? root.step : -root.step);
            newValue = Math.max(minimum, Math.min(newValue, maximum));
            
            root.value = newValue;
            root.moved(newValue); // Sulla rotella di solito si emette sempre subito
        }
    }
}