// generated by gemini
import QtQuick
import QtQuick.Layouts

Item {
    id: root
    
    // --- Proprietà configurabili ---
    property real value: 0
    property real minimum: 0
    property real maximum: 100
    
    property color accentColor: "white"
    property color dotColor: "white"
    property int handleSize: 16
    property int dotSize: 10
    property int barWidth: 2

    property Component handleDelegate: null
    
    // Segnale emesso quando l'utente muove lo slider
    signal moved(real newValue)

    implicitHeight: handleSize
    implicitWidth: 200

    // Calcolo interno della posizione del pallino
    readonly property real visualPos: ((value - minimum) / (maximum - minimum)) * (width - handleSize)

    // Barra di sfondo
    Rectangle {
        anchors.verticalCenter: parent.verticalCenter
        width: parent.width
        height: barWidth
        color: "#30ffffff"
        radius: 2
        
        // Parte attiva
        Rectangle {
            width: root.visualPos + (root.handleSize / 2) - (root.dotSize/3)
            height: parent.height
            color: root.accentColor
            radius: 2
        }
    }

    Loader {
        id: handleLoader
        x: root.visualPos
        y: (parent.height - height) / 2
        width: root.handleSize
        height: root.handleSize
        
        // Se non passiamo nulla da fuori, usiamo un pallino bianco di default
        sourceComponent: root.handleDelegate ? root.handleDelegate : defaultHandle
    }

    // Componente di default (quello semplice)
    Component {
        id: defaultHandle
        // Rectangle {
        //     radius: root.dotSize / 2
        //     color: root.dotColor
        // }
        // Pallino
        Rectangle {
            // id: handle
            // x: root.visualPos
            // y: (parent.height - height) / 2
            width: root.dotSize; height: root.dotSize
            radius: width / 2;
            color: "transparent"
            border.color: root.dotColor
            border.width: root.dotSize / 5
        }
    }

    // // Pallino
    // Rectangle {
    //     id: handle
    //     x: root.visualPos
    //     y: (parent.height - height) / 2
    //     width: root.dotSize; height: root.dotSize
    //     radius: width / 2;
    //     color: "transparent"
    //     border.color: root.dotColor
    //     border.width: root.dotSize / 5
        
    //     // Effetto "buco" come nella tua foto
    //     // Rectangle {
    //     //     anchors.centerIn: parent
    //     //     width: parent.width * 0.4; height: width
    //     //     radius: width / 2; color: "#1a1a1a" 
    //     // }
    // }

    // MouseArea {
    //     anchors.fill: parent
    //     onPositionChanged: (mouse) => {
    //         if (pressed) {
    //             let pos = Math.max(0, Math.min(mouse.x - handleSize/2, root.width - handleSize));
    //             let ratio = pos / (root.width - handleSize);
    //             let newValue = minimum + (ratio * (maximum - minimum));
    //             root.moved(newValue); // Emettiamo il segnale
    //         }
    //     }
    //     onPressed: (mouse) => {
    //         let pos = Math.max(0, Math.min(mouse.x - handleSize/2, root.width - handleSize));
    //         let ratio = pos / (root.width - handleSize);
    //         root.moved(minimum + (ratio * (maximum - minimum)));
    //     }
    // }
}