wallpaper {
	monitor = 
    #path = /home/vollpe/.config/wallpapers/purple_city.png
    #path = ~/.config/wallpapers/mistyFlowerForest.jpg
    #path = ~/.config/wallpapers/pink_misty_forest.webp
    #path = /home/vollpe/.config/wallpapers/misty-forest-with-pink-trees-desktop-wallpaper.jpg
    #path = /home/vollpe/.config/wallpapers/StockCake-Enchanted_Blossom_Forest-293591-standard.jpg
    #path = /home/vollpe/.config/wallpapers/sakura_japan.jpg
    #path = /home/vollpe/.config/wallpapers/sakura_bridge.jpg
    #path = /home/vollpe/.config/wallpapers/misty-dawn-forest-stockcake.jpg
    #path = /home/vollpe/.config/wallpapers/misty-forest-dawn-stockcake.jpg
    #path = /home/vollpe/.config/wallpapers/misty-dawn-field-morning-wallpaper-preview.jpg
    #path = /home/vollpe/.config/wallpapers/purple_nothing_wallpaper.jpeg
    
    #path = /home/vollpe/.config/wallpapers/Gemini_dark_pink_forest.png
#     path = /home/vollpe/.config/wallpapers/Gemini_dark_pink_blue_forest.png
    path = /home/vollpe/.config/wallpapers/Gemini_dark_pink_forest_upscaled.png
#     path = /home/vollpe/.config/wallpapers/Gemini_dark_pink_blue_forest_upscaled.png
    fit_mode = cover
}
