-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "1920x1080@180hz",
    position = "auto",
    scale    = "1.20",
})

--monitor=,1600x900@60hz,auto,auto

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

local fileManager = "kitty yazi"

local menu = "rofi -show drun"

local browser = "firefox"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = waybar & hyprpaper & firefox

-- exec-once = waybar & hyprpaper


--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

--env = XCURSOR_SIZE,24

hl.env("HYPRCURSOR_SIZE", 15)

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-classic")

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 10,
        border_size = 3,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
--         col.active_border = "rgba(FF82F5FF)",
--         col.inactive_border = "rgba(E164D766)",

        ["col.active_border"] = "#FF82F5FF",
        ["col.inactive_border"] = "#E164D766",

        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        -- master 
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 0.9,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 10,
            --3#10
            passes = 2,
            --3#1
            new_optimizations = true,
            vibrancy = 0.1696,
            popups_ignorealpha = 0.0
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

-- hl.config({
--     animations = {
--         enabled = true,
--         
--         -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
--         --        NAME,           X0,   Y0,   X1,   Y1
--         -- Default animations, see https://wiki.hypr.land/Configuring/Animations/
--         --           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
--         --popin 30%
--         --popin 30%
--     },
-- })

-- 1. Configurazione Generale e Bezier
-- 1. Attiviamo il motore delle animazioni
-- 1. Attiviamo il motore delle animazioni generale
hl.config({
    animations = {
        enabled = true,
    },
})

-- 2. Registriamo le curve Bezier con le coordinate corrette
-- hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
-- hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
-- hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1} } })
-- hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1} } })
-- hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1} } })

hl.curve("easeOutQuint",   { type = "spring", stiffness = 100, dampening = 15, mass = 1.0 })
hl.curve("easeInOutCubic", { type = "spring", stiffness = 140, dampening = 18, mass = 1.0 })
hl.curve("linear",         { type = "spring", stiffness = 80,  dampening = 20, mass = 1.0 }) -- Più smorzata, rimbalzo quasi zero
hl.curve("almostLinear",   { type = "spring", stiffness = 90,  dampening = 17, mass = 1.0 })
hl.curve("quick",          { type = "spring", stiffness = 220, dampening = 12, mass = 0.8 }) -- Molto reattiva e scattante

-- 3. Applichiamo le singole animazioni usando la chiave esplicita 'bezier'
hl.animation({ leaf = "global",         enabled = true, speed = 10,   spring = "default" })
hl.animation({ leaf = "border",         enabled = true, speed = 5.39, spring = "easeOutQuint" })
hl.animation({ leaf = "windows",        enabled = true, speed = 4.79, spring = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",      enabled = true, speed = 4.1,  spring = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "windowsOut",     enabled = true, speed = 1.49, spring = "linear",       style = "slide" })
hl.animation({ leaf = "fadeIn",         enabled = true, speed = 1.73, spring = "almostLinear" })
hl.animation({ leaf = "fadeOut",        enabled = true, speed = 1.46, spring = "almostLinear" })
hl.animation({ leaf = "fade",           enabled = true, speed = 3.03, spring = "quick" })
hl.animation({ leaf = "layers",         enabled = true, speed = 3.81, spring = "easeOutQuint" })
hl.animation({ leaf = "layersIn",       enabled = true, speed = 2,    spring = "easeOutQuint", style = "popin" })
hl.animation({ leaf = "layersOut",      enabled = true, speed = 1.5,  spring = "linear",       style = "popin" })
hl.animation({ leaf = "fadeLayersIn",   enabled = true, speed = 1.79, spring = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut",  enabled = true, speed = 1.39, spring = "almostLinear" })
hl.animation({ leaf = "workspaces",     enabled = true, speed = 1.75, spring = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesIn",   enabled = true, speed = 1.75, spring = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesOut",  enabled = true, speed = 1.75, spring = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "zoomFactor",     enabled = true, speed = 7,    spring = "quick" })

-- Le regole speciali per i layer che disattivano le animazioni su hyprshot, quickshell ecc.
hl.layer_rule({ match = { namespace = "selection" }, no_anim = true })
hl.layer_rule({ match = { namespace = "hyprshot" }, no_anim = true })
hl.layer_rule({ match = { namespace = "wlogout" }, no_anim = true })
hl.layer_rule({ match = { namespace = "quickshell" }, no_anim = true })
hl.layer_rule({ match = { namespace = "quickshell" }, blur = true, ignore_alpha = 0.0  })

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrule = bordersize 0, floating:0, onworkspace:f[1]

-- windowrule = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        --     pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "it",
        --it
--         kb_variant = {  },
--         kb_model = {  },
--         kb_options = {  },
--         kb_rules = {  },
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures

-- gesture = 3, horizontal, workspace

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
        name = "usb-optical-mouse",
        sensitivity = 0,
})
-- NOTE: Section 'device' may be a plugin or custom section; verify the output

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("kitty yazi"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

-- makes the window floating (can be resized)

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("rofi -show drun"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle, master the window with a floating size (can be resized)

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle, swaps the divisione from vertical to horizontal

-- bind = $mainMod, Y, exec, killall waybar; waybar & disown

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("firefox"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "A", hl.dsp.exec_cmd("kitty fresh /home/vollpe/.config/APPS.txt"))

-- apre un file di testo con tutte le app usate

hl.bind(mainMod .. " + " .. "K", hl.dsp.exec_cmd("hyprpicker -an"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region -o ~/Pictures/Screenshots/ -f Screenshot-$(date +%F_%T).png -z"))

-- screenshot of a region 

hl.bind("ALT" .. " + " .. "f4", hl.dsp.exec_cmd("wlogout -b 6"))

hl.bind("ALT + tab", hl.dsp.focus({workspace = "previous_per_monitor"}))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))


hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({direction = "left"}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({direction = "right"}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({direction = "up"}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({direction = "down"}))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.window.resize({x = -50, y = 0, relative=true}))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.window.resize({x = 50, y = 0, relative=true}))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "up", hl.dsp.window.resize({x = 0, y = -50, relative=true}))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.window.resize({x = 0, y = 50, relative=true}))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "G", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. "+" .. "F", hl.dsp.window.fullscreen({mode = "maximized"}))

hl.bind(mainMod .. " + Z", hl.dsp.window.center())

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

-- super+right_mouse to drag

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- super+left_mouse to resize

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.gesture({fingers = 3, direction = "horizontal", action = "workspace"})

-- hl.gesture({fingers = 3,
--             direction = "up",
--             action = function()
--                 hl.dsp.focus({workspace = "special:magic"})
--             end
-- })
-- hl.gesture({fingers = 4,
--             direction = "left",
--             action = function()
--                 hl.dsp.focus({ direction = "left" }) 
--             end
-- })
-- hl.gesture({fingers = 4,
--             direction = "right",
--             action = function()
--                 hl.dsp.focus({direction = "right"}) 
--             end
-- })
-- hl.gesture({fingers = 4,
--             direction = "up",
--             action = function()
--                 hl.dsp.focus({direction = "up"}) 
--             end
-- })
-- hl.gesture({fingers = 4,
--             direction = "down",
--             action = function()
--                 hl.dsp.focus({direction = "down"}) 
--             end
-- })
--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule

-- windowrule = float,class:^(kitty)$,title:^(kitty)$

hl.window_rule({
    name  = "suppress-maximize-events match:class=.*",
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags match:class=$match:title=$match:xwayland=true match:float=true match:fullscreen=false match:pin=false",
    no_focus = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("qs & hyprpaper & fcitx5 -d --replace")
end)
